# -*- coding: utf-8 -*-
"""cs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14rFDBXIGhYtML54D2LxhpxjmWsk0HDWc
"""

import cv2
import os

split_byte_to_bits = lambda data: [data >> 5, (data>>2)& 0x7, data & 0x3]
extract_nbits_of_byte = lambda band, n : band & (2**n-1)
merge_bits = lambda rbits,gbits, bbits :(((rbits<< 3) | gbits) << 2) | bbits

def generate_embedded_imagename(vessel_img):

    if '/' in vessel_img:
        temp = vessel_img.split('/')
        temp[-1] = 'e_'+ temp[-1]
        ename = '/'.join(temp)
        if ename.lower().endswith('.jpg'):
            ename = ename.replace('.jpg', '.png')
        elif ename.lower().endswith('.jpeg'):
            ename = ename.replace('.jpeg', '.png')
        return ename
    else:
        print('Use / as separator')
        return None

def generate_header(doc):

    name = doc.split('/')[-1]

    l = len(name)
    if l >20:
        name = name[l-20:]
    elif l <20:
        name = name.rjust(20, '*')

    size = str(os.path.getsize(doc))
    size = size.rjust(10, '*')
    return name+size

def embed(vessel_image, doc):

    if not os.path.exists(vessel_image) :
        print(vessel_image, 'not found')
        return None
    if not os.path.exists(doc) :
        print(doc, 'not found')
        return None


    mem_image = cv2.imread(vessel_image, cv2.IMREAD_COLOR)

    h,w,_ = mem_image.shape


    doc_size = os.path.getsize(doc)


    header = generate_header(doc)


    capacity =  h*w
    header_length = len(header)

    if doc_size + header_length > capacity:
        print(doc ,' too large to fit in', vessel_image )
        return None


    cnt = 0

    file_handle = open(doc, 'rb')

    flag = True
    i =0
    while i < h and flag:
        j = 0
        while j < w and flag:
            pixel = mem_image[i,j]
            blue = pixel[0]
            green = pixel[1]
            red = pixel[2]

            if cnt < header_length:

                data = ord(header[cnt])
            else:

                data = file_handle.read(1)
                if data:
                    data = int.from_bytes(data, byteorder='big')
                else:

                    flag = False
                    continue

            bits = split_byte_to_bits(data)


            red = (red & (~0x7)) | bits[0]
            green = (green & (~0x7)) | bits[1]
            blue = (blue & (~0x3)) | bits[2]


            mem_image[i, j, 0] = blue
            mem_image[i, j, 1] = green
            mem_image[i, j, 2] = red

            cnt+=1
            j+=1
        i+=1

    file_handle.close()

    target_image = generate_embedded_imagename(vessel_image)
    cv2.imwrite(target_image, mem_image)

    return target_image

def extract(embedded_image, target_folder):
    if not os.path.exists(embedded_image):
        print(embedded_image, 'not found')
        return None
    if not os.path.exists(target_folder):
        print(target_folder, 'not found')
        return None


    mem_img = cv2.imread(embedded_image, cv2.IMREAD_COLOR)


    h,w,_ = mem_img.shape

    header_length = 30
    flag = True
    i =0
    cnt =0
    header = ''
    while i < h and flag:
        j =0
        while j < w and flag:

            pixel = mem_img[i,j]
            blue = pixel[0]
            green = pixel[1]
            red = pixel[2]


            red_bits = extract_nbits_of_byte(red, 3)
            green_bits = extract_nbits_of_byte(green, 3)
            blue_bits = extract_nbits_of_byte(blue, 2)


            data = merge_bits(red_bits, green_bits, blue_bits)

            if cnt < header_length:
                header = header + chr(data)
            else:
                if cnt == header_length:
                    print(header)
                    filename = header[:20].strip('*')
                    filesize = int(header[20:].strip('*'))


                    file_handle = open(target_folder+'/'+filename, 'wb')

                if cnt - header_length < filesize:

                    data = int.to_bytes(int(data), 1, byteorder='big')

                    file_handle.write(data)
                else:
                    file_handle.close()
                    flag = False

            cnt+=1
            j+=1
        i+=1
    return  target_folder + '/' + filename

def main():
    while True:
        print('1. Embed')
        print('2. Extract')
        print('3. Exit')
        print('Enter Choice ')
        ch = int(input())

        if ch == 1:
            print('Enter vessel image path')
            vessel_img = input()
            print('Enter file to embed')
            doc = input()

            result =  embed(vessel_img, doc)
            if result != None:
                print('Embedding Done, result: ', result)
            else:
                print('Embedding Failed')
        elif ch == 2:
            print('Enter embedded image path')
            embedded_image = input()
            print('Enter target folder for saving the extracted file')
            target_folder = input()

            result = extract(embedded_image, target_folder)
            if result != None:
                print('Extraction Done, result: ', result)
            else:
                print('Extraction Failed')
        elif ch == 3:
            break
        else:
            print('Wrong Choice')

main()